[[redirects]]
  from = "/api/*"
  to = "https://bps.boopursal.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://boopursal.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "3600"

[build]
  command = "yarn build"  # Remplace par ta commande de build spécifique
  publish = "build"       # Répertoire de publication

[context.production.environment]
  YARN_ENABLED = "true"    # Utiliser Yarn pour installer les dépendances
